package com.example.model;

public enum ECategory {
    CATEGORY_FANTASY,
    CATEGORY_ADVENTURE,
    CATEGORY_ROMANCE,
    CATEGORY_CONTEMPORARY,
    CATEGORY_DYSTOPIAN,
    CATEGORY_MYSTERY,
    CATEGORY_HORROR,
    CATEGORY_THRILLER,
    CATEGORY_PARANORMAL,
    CATEGORY_HISTORICAL_FICTION,
    CATEGORY_SCIENCE_FICTION,
    CATEGORY_CHILDREN,
    CATEGORY_MEMOIR,
    CATEGORY_COOKBOOK,
    CATEGORY_ART,
    CATEGORY_SELF_HELP,
    CATEGORY_PERSONAL_DEVELOPMENT,
    CATEGORY_MOTIVATIONAL,
    CATEGORY_HEALTH,
    CATEGORY_HISTORY,
    CATEGORY_TRAVEL,
    CATEGORY_GUIDE,
    CATEGORY_RELATIONSHIPS,
    CATEGORY_HUMOR
}
