package com.example.model;

public enum EGenre {
    GENRE_FANTASY,
    GENRE_ADVENTURE,
    GENRE_ROMANCE,
    GENRE_CONTEMPORARY,
    GENRE_DYSTOPIAN,
    GENRE_MYSTERY,
    GENRE_HORROR,
    GENRE_THRILLER,
    GENRE_PARANORMAL,
    GENRE_HISTORICAL_FICTION,
    GENRE_SCIENCE_FICTION,
    GENRE_CHILDREN,
    GENRE_MEMOIR,
    GENRE_COOKBOOK,
    GENRE_ART,
    GENRE_SELF_HELP,
    GENRE_PERSONAL_DEVELOPMENT,
    GENRE_MOTIVATIONAL,
    GENRE_HEALTH,
    GENRE_HISTORY,
    GENRE_TRAVEL,
    GENRE_GUIDE,
    GENRE_RELATIONSHIPS,
    GENRE_HUMOR
}
